import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";

const gabarito = Gabarito({
  subsets: ["latin"],
  variable: "--font-gabarito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gabarito.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
